# Generated by Django 5.1.5 on 2025-02-05 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
