# Generated by Django 5.1.5 on 2025-02-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customer_delete_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
